apiVersion: v1
kind: Namespace
metadata:
    name: dev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-dev-pv-volume
  namespace: dev
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: tekton-dev-pv-claim
    namespace: dev
spec:
    storageClassName: manual
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
          storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-dev-env
  namespace: dev
  labels:
    app: tekton-dev-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-dev-env
  template:
    metadata:
      labels:
        app: tekton-dev-env
    spec:
      containers:
      - image: popcor255/tekton-dev-env:latest
        name: tekton-dev-env 
        resources:
          requests:
            cpu: "200m"
            memory: "2G"
        envFrom:
        - secretRef:
            name: tekton-dev-secret
        volumeMounts:
        - mountPath: /mnt/data
          name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: tekton-dev-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: tekton-dev-env
spec:
  type: NodePort
  selector:
    app: tekton-dev-env
  ports:
    - port: 20
      targetPort: 20
      nodePort: 30007